---
# tasks file for AIX-CIS
- name: Check OS version and family
  ansible.builtin.assert:
      that: (ansible_facts.distribution == 'AIX') and ansible_facts.distribution_major_version is version_compare('7', '==') and ansible_facts.distribution_release is version_compare('3', '==')
      fail_msg: "Unsupported OSs. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }}.{{ ansible_facts.distribution_release }} is not supported."
      success_msg: "This role is running against a supported OS {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }}.{{ ansible_facts.distribution_release }}"
  when:
      - os_check
  tags:
      - always

- name: Run Section 2 tasks
  ansible.builtin.import_tasks:
      file: section_2/main.yml
  when: aixcis_section2
  tags:
      - aixcis_section2
