---

- name: "2.6 Enforce Allowlist aka Trusted Execution Checks"

  tags:
    - level_2

  block:
    - name: Enabling TE
      ansible.builtin.shell: >
        set -o pipefail && trustchk -p TE 2>&1 | grep -q "=ON"
        && echo "TE_ENABLED"
        || trustchk -p TE=ON
      args:
        executable: /bin/bash
      register: te_status
      changed_when: te_status.stdout != 'TE_ENABLED'

    - name: Enabling STOP_UNTRUSTD
      ansible.builtin.shell: >
        set -o pipefail && trustchk -p STOP_UNTRUSTD 2>&1 | grep -q "=ON"
        && echo "STOP_UNTRUSTD_ENABLED"
        || trustchk -p STOP_UNTRUSTD=ON
      args:
        executable: /bin/bash
      register: stop_untrustd_status
      changed_when: stop_untrustd_status.stdout != 'STOP_UNTRUSTD_ENABLED'

    - name: Enabling STOP_ON_CHKFAIL
      ansible.builtin.shell: >
        set -o pipefail && trustchk -p STOP_ON_CHKFAIL 2>&1 | grep -q "=ON"
        && echo "STOP_ON_CHKFAIL_ENABLED"
        || trustchk -p STOP_ON_CHKFAIL=ON
      args:
        executable: /bin/bash
      register: stop_on_chkfail_status
      changed_when: stop_on_chkfail_status.stdout != 'STOP_ON_CHKFAIL_ENABLED'
